language: java
jdk:
  - oraclejdk7

before_script:
  - "echo $JAVA_OPTS"
  - "export JAVA_OPTS=-Xmx6g"

before_cache:
  - rm -f $HOME/.gradle/caches/modules-2/modules-2.lock

cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
